//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int MaTeam { get; set; }
        public string Ten { get; set; }
        public string ChucVu { get; set; }
        public string HinhAnh { get; set; }
        public string TramNgon { get; set; }
    }
}
